### ISSUE TITLE
Stackoverflow when trying to analyze Kotlin Code

### ISSUE THREAD

**Issue by tikurahul** [marcelkliemannel/intellij-byte-code-plugin#6] opened 2021-07-16 22:47 UTC
Here is a truncated version of the stack trace:

```
java.lang.StackOverflowError
	at com.intellij.util.messages.impl.MessageBusImpl.deliverImmediately(MessageBusImpl.java:556)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverImmediately(MessageBusConnectionImpl.java:60)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.dispatchPendingEvents(FileManagerImpl.java:306)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:355)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:154)
	at dev.turingcomplete.intellijbytecodeplugin.openclassfiles._internal.OpenClassFilesTask.consumeFiles(OpenClassFilesTask.kt:102)
	at dev.turingcomplete.intellijbytecodeplugin.openclassfiles._internal.OpenClassFilesTask.consumePsiFiles(OpenClassFilesTask.kt:143)
	at dev.turingcomplete.intellijbytecodeplugin.openclassfiles._internal.OpenClassFilesTask.consumeFiles(OpenClassFilesTask.kt:113)
	at dev.turingcomplete.intellijbytecodeplugin.openclassfiles._internal.OpenClassFilesTask.consumePsiFiles(OpenClassFilesTask.kt:143)
	at dev.turingcomplete.intellijbytecodeplugin.openclassfiles._internal.OpenClassFilesTask.consumeFiles(OpenClassFilesTask.kt:113)
```

To reproduce, just create a `New project` in Intellij Idea, and create a new `Kotlin` source file. 

```kotlin

package com.example

class Sample {
}
```

Right click the editor and select `Analyze Byte Code` and see this `StackOverflowError`.
*Note*: I did not create a Gradle Project. I created an IML project. This problem went away once I build the module using the `Build` menu.

P.S: It works incredibly well with Java files, and thanks for making this available.

**Comment by marcelkliemannel** [comment] 2021-07-20 19:59
Thank you for taking the time to submit a bug ticket.

I was able to reproduce the problem when I run the class file open action while IntelliJ is indexing the project. But not outside of that state. 

In general, the plugin should work fine with Kotlin code. Firstly because I use it regularly for that and secondly because there is a unit test that tries to open the entire Kotlin standard library. 

I included a check that prevents the action from executing when indexing is running and displays a proper error message. The fix is released as version 2.0.1 (it takes 1-2 days until JetBrains approves the new version). Maybe you could evaluate with this version if the problem still exists.

**Closed by marcelkliemannel** 2021-07-20 19:59 UTC
Labels: bug
